
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:24:36 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'uart.ucf'
####################################################################################

# "GCLK"
set_property PACKAGE_PIN Y9 [get_ports clk]
# /home/scott/project/uart/rtl/uart.ucf:1
# The conversion of 'IOSTANDARD' constraint on 'net' object 'clk' has been applied to the port object 'clk'.
set_property IOSTANDARD LVCMOS33 [get_ports clk]
# "BTNU"
set_property PACKAGE_PIN T18 [get_ports reset]
# /home/scott/project/uart/rtl/uart.ucf:2NET BTNU          LOC = T18  | IOSTANDARD=LVCMOS18;  # "BTNU"
# The conversion of 'IOSTANDARD' constraint on 'net' object 'reset' has been applied to the port object 'reset'.
set_property IOSTANDARD LVCMOS18 [get_ports reset]
#NET tx         LOC = AB6  | IOSTANDARD=LVCMOS33;  # "JC1_N"
#NET rx         LOC = Y4   | IOSTANDARD=LVCMOS33;  # "JC2_P"
# "JB2"
set_property PACKAGE_PIN W11 [get_ports tx]
# /home/scott/project/uart/rtl/uart.ucf:5
# The conversion of 'IOSTANDARD' constraint on 'net' object 'tx' has been applied to the port object 'tx'.
set_property IOSTANDARD LVCMOS33 [get_ports tx]
# "JB3"
set_property PACKAGE_PIN V10 [get_ports rx]
# /home/scott/project/uart/rtl/uart.ucf:6
# The conversion of 'IOSTANDARD' constraint on 'net' object 'rx' has been applied to the port object 'rx'.
set_property IOSTANDARD LVCMOS33 [get_ports rx]

# "SW0"
set_property PACKAGE_PIN F22 [get_ports {ctrl[0]}]
# /opt/project/dn/project_1/project_1.srcs/constrs_1/new/test.ucf:1
# The conversion of 'IOSTANDARD' constraint on 'net' object 'a[0]' has been applied to the port object 'a[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {ctrl[0]}]
# "SW1"
set_property PACKAGE_PIN G22 [get_ports {ctrl[1]}]
# /opt/project/dn/project_1/project_1.srcs/constrs_1/new/test.ucf:2
# The conversion of 'IOSTANDARD' constraint on 'net' object 'a[1]' has been applied to the port object 'a[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {ctrl[1]}]
# "SW2"
set_property PACKAGE_PIN H22 [get_ports {ctrl[2]}]
# /opt/project/dn/project_1/project_1.srcs/constrs_1/new/test.ucf:3
# The conversion of 'IOSTANDARD' constraint on 'net' object 'a[2]' has been applied to the port object 'a[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {ctrl[2]}]
# "SW3"
set_property PACKAGE_PIN F21 [get_ports {ctrl[3]}]
# /opt/project/dn/project_1/project_1.srcs/constrs_1/new/test.ucf:4
# The conversion of 'IOSTANDARD' constraint on 'net' object 'a[3]' has been applied to the port object 'a[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {ctrl[3]}]
# "SW4"
set_property PACKAGE_PIN H19 [get_ports {ctrl[4]}]
# /opt/project/dn/project_1/project_1.srcs/constrs_1/new/test.ucf:5
# The conversion of 'IOSTANDARD' constraint on 'net' object 'a[4]' has been applied to the port object 'a[4]'.
set_property IOSTANDARD LVCMOS18 [get_ports {ctrl[4]}]
# "SW5"
set_property PACKAGE_PIN H18 [get_ports {ctrl[5]}]
# /opt/project/dn/project_1/project_1.srcs/constrs_1/new/test.ucf:6
# The conversion of 'IOSTANDARD' constraint on 'net' object 'a[5]' has been applied to the port object 'a[5]'.
set_property IOSTANDARD LVCMOS18 [get_ports {ctrl[5]}]
# "SW6"
set_property PACKAGE_PIN H17 [get_ports dn_device_debug_en]
# /opt/project/dn/project_1/project_1.srcs/constrs_1/new/test.ucf:7
# The conversion of 'IOSTANDARD' constraint on 'net' object 'a[6]' has been applied to the port object 'a[6]'.
set_property IOSTANDARD LVCMOS18 [get_ports dn_device_debug_en]
# "SW7"
set_property PACKAGE_PIN M15 [get_ports dn_host_debug_en]
# /opt/project/dn/project_1/project_1.srcs/constrs_1/new/test.ucf:8
# The conversion of 'IOSTANDARD' constraint on 'net' object 'a[7]' has been applied to the port object 'a[7]'.
set_property IOSTANDARD LVCMOS18 [get_ports dn_host_debug_en]

# "LD0"
set_property PACKAGE_PIN T22 [get_ports {data_obs[0]}]
# /home/scott/project/uart/rtl/uart.ucf:7
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data_obs[0]' has been applied to the port object 'data_obs[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data_obs[0]}]
# "LD1"
set_property PACKAGE_PIN T21 [get_ports {data_obs[1]}]
# /home/scott/project/uart/rtl/uart.ucf:8
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data_obs[1]' has been applied to the port object 'data_obs[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data_obs[1]}]
# "LD2"
set_property PACKAGE_PIN U22 [get_ports {data_obs[2]}]
# /home/scott/project/uart/rtl/uart.ucf:9
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data_obs[2]' has been applied to the port object 'data_obs[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data_obs[2]}]
# "LD3"
set_property PACKAGE_PIN U21 [get_ports {data_obs[3]}]
# /home/scott/project/uart/rtl/uart.ucf:10
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data_obs[3]' has been applied to the port object 'data_obs[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data_obs[3]}]
# "LD4"
set_property PACKAGE_PIN V22 [get_ports {data_obs[4]}]
# /home/scott/project/uart/rtl/uart.ucf:11
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data_obs[4]' has been applied to the port object 'data_obs[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data_obs[4]}]
# "LD5"
set_property PACKAGE_PIN W22 [get_ports {data_obs[5]}]
# /home/scott/project/uart/rtl/uart.ucf:12
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data_obs[5]' has been applied to the port object 'data_obs[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data_obs[5]}]
# "LD6"
set_property PACKAGE_PIN U19 [get_ports {data_obs[6]}]
# /home/scott/project/uart/rtl/uart.ucf:13
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data_obs[6]' has been applied to the port object 'data_obs[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data_obs[6]}]
# "LD7"
set_property PACKAGE_PIN U14 [get_ports {data_obs[7]}]
# /home/scott/project/uart/rtl/uart.ucf:14
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data_obs[7]' has been applied to the port object 'data_obs[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data_obs[7]}]
